# Generated by Django 4.2.7 on 2026-03-26 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic')], max_length=20)),
                ('area', models.CharField(choices=[('KAUSA', 'Kausa'), ('AMRUT_NAGAR', 'Amrut Nagar'), ('STATION_ROAD', 'Station Road')], max_length=50)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Healthcare Facilities',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('KAUSA', 'Kausa'), ('AMRUT_NAGAR', 'Amrut Nagar'), ('STATION_ROAD', 'Station Road')], max_length=50)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('is_24_7', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(choices=[('PEDIATRIC', 'Pediatrician'), ('CARDIAC', 'Cardiac Expert'), ('GENERAL', 'General Physician'), ('GYNAE', 'Gynaecologist'), ('ORTHO', 'Orthopaedic'), ('DERM', 'Dermatologist'), ('ENT', 'ENT Specialist')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('timing_slots', models.JSONField(default=dict, help_text='e.g. {"mon-sat": "10:00-13:00", "eve": "18:00-21:00"}')),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='healthcare.healthcarefacility')),
            ],
            options={
                'ordering': ['specialty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('available_beds', models.PositiveIntegerField(default=0)),
                ('icu_total', models.PositiveIntegerField(default=0)),
                ('icu_available', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bed_status', to='healthcare.healthcarefacility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bed Status',
                'verbose_name_plural': 'Bed Statuses',
            },
        ),
    ]
