# Generated by Django 4.2.7 on 2026-03-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Portal login user for this doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Portal login user for this facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
