# Generated by Django 4.2.7 on 2026-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_doctor_user_healthcarefacility_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Short ad text displayed in the banner.', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Optional banner image. If set, shown instead of text.', null=True, upload_to='ads/')),
                ('link_url', models.URLField(blank=True, help_text='Optional tap-through URL.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm_qr_image', models.ImageField(blank=True, help_text='Paytm / UPI QR code image shown in the "Thank You" donate popup.', null=True, upload_to='donate/')),
                ('donate_name', models.CharField(default='Mumbra Care', help_text='Name shown below the QR code.', max_length=100)),
                ('donate_upi_id', models.CharField(blank=True, help_text='UPI ID shown below the QR code (e.g. mumbracare@paytm).', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
