# Generated by Django 4.2.7 on 2026-04-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0003_advertisement_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Portal login user for this pharmacy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]